name: Ruby
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failures }}
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7]
        allow-failures: [false]
        include:
          - ruby: head
            allow-failures: true
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle config set without 'development'
        bundle install --jobs 4 --retry 3
        bundle exec rake
    - name: Send test coverage report to codecov.io
      uses: codecov/codecov-action@v1
